# Generated by Django 4.1.3 on 2022-11-24 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='all_assets')),
                ('device_serial_number', models.CharField(max_length=400, unique=True)),
                ('short_descriptions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=400)),
                ('employee_image', models.ImageField(upload_to='employee')),
                ('employee_designation', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Assets_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_issue_date', models.DateField(default=datetime.date.today, verbose_name='Device issue date')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due Date')),
                ('return_device', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllapp.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controllapp.employee')),
            ],
        ),
    ]
